#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/4eburnetd
CONF=/etc/config/4eburnet
PIDFILE=/var/run/4eburnetd.pid

start_service() {
    [ -f "$CONF" ] || return 1
    [ -x "$PROG" ] || return 1

    procd_open_instance
    procd_set_param command "$PROG" -f
    procd_set_param respawn 3600 5 5
    procd_set_param pidfile "$PIDFILE"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rm -f "$PIDFILE"
}

reload_service() {
    "$PROG" reload
}

service_triggers() {
    procd_add_reload_trigger "4eburnet"
}
