include $(TOPDIR)/rules.mk

LUCI_TITLE:=Phoenix Router — панель управления
LUCI_DEPENDS:=+phoenix-core
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

$(eval $(call BuildPackage,luci-app-phoenix))
